server {
    listen 4003;
    listen [::]:4003;

    server_name _;

    root /srv/github-sites/simple-site/current/public;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    access_log /var/log/nginx/simple-site-direct.access.log;
    error_log /var/log/nginx/simple-site-direct.error.log;
}
